name: fetch-fixtures

on:
  workflow_dispatch:
    inputs:
      date:
        description: 'Data (YYYY-MM-DD), opzionale'
        required: false
  schedule:
    - cron: '0 3 * * *'

jobs:
  fetch:
    runs-on: ubuntu-latest
    env:
      API_FOOTBALL_KEY: ${{ secrets.API_FOOTBALL_KEY }}
      API_FOOTBALL_PERSIST_FIXTURES: 'true'
      BET_DATA_DIR: 'data'
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install rich==13.7.1 schedule==1.2.1 python-dotenv==1.0.1 pytest httpx requests
          python -m pip install -r requirements.txt
      - name: Debug Python & pip
        run: |
          python --version
          which python
          python -m pip --version
          python -m pip list
      - name: Fetch fixtures
        env:
          DATE: ${{ github.event.inputs.date }}
          PYTHONPATH: src
        run: |
          python scripts/fetch_fixtures.py
      - name: Upload latest fixtures artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: fixtures-latest
          path: data/fixtures_latest.json
          if-no-files-found: ignore
