name: Fetch Pipeline

on:
  workflow_dispatch:
  schedule:
    - cron: "5 * * * *"
  push:
    branches: ["main"]

concurrency:
  group: fetch-pipeline
  cancel-in-progress: true

jobs:
  fetch-run:
    runs-on: ubuntu-latest
    timeout-minutes: 25
    permissions:
      contents: read
      actions: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: pip-${{ runner.os }}-${{ hashFiles('requirements*.txt', 'pyproject.toml', 'setup.cfg') }}
          restore-keys: |
            pip-${{ runner.os }}-

      - name: Install dependencies (dev)
        run: |
          set -e
          if [ -f requirements-dev.txt ]; then
            pip install -r requirements-dev.txt
          elif [ -f requirements.txt ]; then
            pip install -r requirements.txt
            pip install pytest httpx prometheus-client
          else
            echo "Nessun requirements*.txt trovato: installo base minima"
            pip install pytest httpx prometheus-client fastapi uvicorn
          fi
          echo "== Installed packages =="
          pip list

      - name: Export PYTHONPATH
        run: echo "PYTHONPATH=$PWD/src" >> $GITHUB_ENV

      - name: Smoke import
        env:
          PYTHONPATH: ${{ env.PYTHONPATH }}
        run: |
          python - <<'EOF'
          import sys
          print("sys.path OK, contains src?:", any(p.endswith("/src") for p in sys.path))
          import core
          print("Import core OK ->", core.__file__)
          EOF

      - name: Run tests
        env:
          PYTHONPATH: ${{ env.PYTHONPATH }}
        run: pytest -q

      - name: Run fetch pipeline
        env:
          PYTHONPATH: ${{ env.PYTHONPATH }}
          API_FOOTBALL_KEY: ${{ secrets.API_FOOTBALL_KEY }}
          ENABLE_ODDS_INGESTION: ${{ vars.ENABLE_ODDS_INGESTION }}
          ENABLE_PREDICTIONS: ${{ vars.ENABLE_PREDICTIONS }}
          ENABLE_PREDICTIONS_USE_ODDS: ${{ vars.ENABLE_PREDICTIONS_USE_ODDS }}
          ENABLE_VALUE_DETECTION: ${{ vars.ENABLE_VALUE_DETECTION }}
          ENABLE_VALUE_ALERTS: ${{ vars.ENABLE_VALUE_ALERTS }}
          ENABLE_ROI_TRACKING: ${{ vars.ENABLE_ROI_TRACKING }}
          ENABLE_VALUE_HISTORY: ${{ vars.ENABLE_VALUE_HISTORY }}
          ROI_MIN_EDGE: ${{ vars.ROI_MIN_EDGE }}
        run: |
          python scripts/fetch_fixtures.py
          echo "---- Elenco file data/ ----"
          find data -maxdepth 4 -type f -print || true

      - name: Show key outputs
        if: always()
        run: |
          for f in \
            data/odds/odds_latest.json \
            data/predictions/latest_predictions.json \
            data/value_alerts/value_alerts.json \
            data/roi/roi_metrics.json; do
            if [ -f "$f" ]; then
              echo "----- $f -----"
              head -n 80 "$f"
            fi
          done

      - name: Upload data artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: pipeline-data
          path: data
          retention-days: 7
