name: fetch-fixtures
on:
  workflow_dispatch:
    inputs:
      date:
        description: 'YYYY-MM-DD (opzionale)'
        required: false
        type: string
  schedule:
    - cron: '0 3 * * *'  # 03:00 UTC

jobs:
  fetch:
    runs-on: ubuntu-latest
    env:
      API_FOOTBALL_KEY: ${{ secrets.API_FOOTBALL_KEY }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run fetch
        run: |
          python scripts/fetch_fixtures.py
      - name: Upload artifact (fixtures-latest)
        if: ${{ hashFiles('data/fixtures_latest.json') != '' }}
        uses: actions/upload-artifact@v4
        with:
          name: fixtures-latest
          path: data/fixtures_latest.json
