name: Fetch Pipeline

on:
  workflow_dispatch:
  schedule:
    - cron: "5 * * * *"
  push:
    branches: ["main"]

concurrency:
  group: fetch-pipeline
  cancel-in-progress: true

jobs:
  fetch-run:
    runs-on: ubuntu-latest
    timeout-minutes: 25
    permissions:
      contents: read
      actions: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: pip-${{ runner.os }}-${{ hashFiles('requirements*.txt', 'pyproject.toml', 'setup.cfg') }}
          restore-keys: |
            pip-${{ runner.os }}-

      - name: Install dependencies (robust)
        run: |
          set -e
          if [ -f requirements-dev.txt ]; then
            python -m pip install -r requirements-dev.txt
          elif [ -f requirements.txt ]; then
            python -m pip install -r requirements.txt
            python -m pip install pytest httpx prometheus-client
          else
            python -m pip install fastapi uvicorn pydantic requests prometheus-client pytest httpx
          fi
          python -m pip install --upgrade pytest httpx prometheus-client

      - name: Export PYTHONPATH
        run: echo "PYTHONPATH=$PWD/src" >> $GITHUB_ENV

      - name: Show selected provider scope
        run: |
          echo "PROVIDER_SOURCE=${{ vars.PROVIDER_SOURCE }}"
          echo "FOOTBALL_DATA_LEAGUES=${{ vars.FOOTBALL_DATA_LEAGUES }}"
          echo "UPCOMING_DAYS=${{ vars.UPCOMING_DAYS }}"
          echo "API_FOOTBALL_DEFAULT_LEAGUE_ID=${{ vars.API_FOOTBALL_DEFAULT_LEAGUE_ID }}"
          echo "API_FOOTBALL_DEFAULT_SEASON=${{ vars.API_FOOTBALL_DEFAULT_SEASON }}"
          echo "BET_DATA_DIR=${{ vars.BET_DATA_DIR }}"

      - name: Quick API probe (optional)
        env:
          FOOTBALL_DATA_API_KEY: ${{ secrets.FOOTBALL_DATA_API_KEY }}
        run: |
          python - <<'PY'
          import os, sys
          key = os.getenv("FOOTBALL_DATA_API_KEY")
          print("FOOTBALL_DATA_API_KEY set? ->", bool(key))
          PY

      - name: Run tests
        env:
          PYTHONPATH: ${{ env.PYTHONPATH }}
        run: python -m pytest -q

      - name: Run fetch pipeline
        env:
          PYTHONPATH: ${{ env.PYTHONPATH }}
          # Provider selection
          PROVIDER_SOURCE: ${{ vars.PROVIDER_SOURCE }}
          FOOTBALL_DATA_API_KEY: ${{ secrets.FOOTBALL_DATA_API_KEY }}
          FOOTBALL_DATA_LEAGUES: ${{ vars.FOOTBALL_DATA_LEAGUES }}
          UPCOMING_DAYS: ${{ vars.UPCOMING_DAYS }}
          # Legacy vars (restano per compatibilità)
          API_FOOTBALL_KEY: ${{ secrets.API_FOOTBALL_KEY }}
          API_FOOTBALL_DEFAULT_LEAGUE_ID: ${{ vars.API_FOOTBALL_DEFAULT_LEAGUE_ID }}
          API_FOOTBALL_DEFAULT_SEASON: ${{ vars.API_FOOTBALL_DEFAULT_SEASON }}
          BET_DATA_DIR: ${{ vars.BET_DATA_DIR }}
          ENABLE_ODDS_INGESTION: ${{ vars.ENABLE_ODDS_INGESTION }}
          ENABLE_PREDICTIONS: ${{ vars.ENABLE_PREDICTIONS }}
          ENABLE_PREDICTIONS_USE_ODDS: ${{ vars.ENABLE_PREDICTIONS_USE_ODDS }}
          ENABLE_VALUE_DETECTION: ${{ vars.ENABLE_VALUE_DETECTION }}
          ENABLE_VALUE_ALERTS: ${{ vars.ENABLE_VALUE_ALERTS }}
          ENABLE_ROI_TRACKING: ${{ vars.ENABLE_ROI_TRACKING }}
          ENABLE_VALUE_HISTORY: ${{ vars.ENABLE_VALUE_HISTORY }}
          ROI_MIN_EDGE: ${{ vars.ROI_MIN_EDGE }}
        run: |
          python scripts/fetch_fixtures.py
          find data -maxdepth 4 -type f -print || true

      - name: Show key outputs
        if: always()
        run: |
          for f in \
            data/metrics/last_run.json \
            data/fixtures_latest.json \
            data/odds/odds_latest.json \
            data/predictions/latest_predictions.json \
            data/value_alerts/value_alerts.json; do
            if [ -f "$f" ]; then
              echo "----- $f -----"
              head -n 150 "$f"
            else
              echo "MISSING: $f"
            fi
          done

      - name: Upload data artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: pipeline-data
          path: data
          retention-days: 7
