name: Data pipeline (scheduled)

on:
  schedule:
    - cron: "*/30 * * * *"
  workflow_dispatch:

jobs:
  run-pipeline:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      actions: read
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m venv .venv
          . .venv/bin/activate
          pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          if [ -f backend/api/requirements.txt ]; then pip install -r backend/api/requirements.txt; fi
          if [ -f frontend/gui/requirements.txt ]; then pip install -r frontend/gui/requirements.txt; fi

      - name: Consensus merge
        env:
          PYTHONPATH: .
        run: |
          . .venv/bin/activate
          python scripts/consensus_merge.py \
            --sources-dir data/predictions/sources \
            --odds-file data/odds_latest.json \
            --out data/latest_predictions.json \
            --weights consensus/config.yml \
            --min-models 1

      - name: Fetch model odds (default)
        run: |
          . .venv/bin/activate
          ODDS_PROVIDER=${{ vars.ODDS_PROVIDER || 'model' }} \
          ENABLE_ODDS_INGESTION=${{ vars.ENABLE_ODDS_INGESTION || '1' }} \
          MODEL_ODDS_MARGIN=${{ vars.MODEL_ODDS_MARGIN || '0.0' }} \
          python scripts/fetch_odds.py

      - name: Enrich predictions with odds/edge/value
        run: |
          . .venv/bin/activate
          EFFECTIVE_THRESHOLD=${{ vars.EFFECTIVE_THRESHOLD || '0.03' }} \
          python scripts/enrich_predictions.py

      - name: Fixtures snapshot
        run: |
          . .venv/bin/activate
          python scripts/fixtures_snapshot.py --delta-file data/last_delta.json --out data/fixtures.json || true

      - name: ROI compute
        run: |
          . .venv/bin/activate
          python scripts/roi_compute.py --ledger data/ledger.jsonl --out-metrics data/roi_metrics.json --out-daily data/roi_daily.json --out-history data/roi_history.jsonl --append-history

      - name: Generate value alerts
        run: |
          . .venv/bin/activate
          EFFECTIVE_THRESHOLD=${{ vars.EFFECTIVE_THRESHOLD || '0.03' }} \
          ALERTS_FILTER_STATUS=${{ vars.ALERTS_FILTER_STATUS || '' }} \
          python scripts/value_alerts.py

      - name: Dispatch alerts (optional)
        if: ${{ vars.ALERT_DISPATCH_WEBHOOK != '' }}
        run: |
          . .venv/bin/activate
          ALERT_DISPATCH_WEBHOOK=${{ vars.ALERT_DISPATCH_WEBHOOK }} \
          python scripts/dispatch_alerts.py

      - name: Data retention cleanup
        run: |
          . .venv/bin/activate
          RETENTION_DAYS=${{ vars.RETENTION_DAYS || '14' }} \
          python scripts/retention_cleanup.py

      - name: Upload data artifacts
        uses: actions/upload-artifact@v4
        with:
          name: data-snapshot
          path: |
            data/latest_predictions.json
            data/value_alerts.json
            data/odds_latest.json
            data/last_delta.json
            data/fixtures.json
            data/scoreboard.json
            data/roi_metrics.json
            data/roi_daily.json
            data/roi_history.jsonl
          if-no-files-found: warn
          retention-days: 7

      - name: Commit updated data (optional via repo variable COMMIT_DATA=true)
        if: ${{ vars.COMMIT_DATA == 'true' }}
        run: |
          set -e
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add data/*.json data/*.jsonl || true
          if ! git diff --cached --quiet; then
            git commit -m "chore(data): scheduled update"
            git push
          else:
            echo "No data changes to commit."
          fi
