name: typecheck

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  typecheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install mypy and types
        run: |
          python -m pip install --upgrade pip
          pip install mypy==1.11.2 types-requests
      - name: Run mypy
        run: mypy --pretty src