name: typecheck

on:
  push:
    branches:
      - main
      - quality_setup
  pull_request:
    branches:
      - main
      - quality_setup

jobs:
  mypy:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          # (Se mypy NON fosse nel requirements.txt, aggiungi qui:)
          # pip install mypy==1.11.2

      - name: Verify mypy installation
        run: |
          which mypy || (echo "mypy non trovato" && exit 1)
          mypy --version

      - name: Run mypy
        env:
          MYPYPATH: src   # ridondante ma innocuo
        run: |
          mypy --config-file mypy.ini --pretty src
